export const CLAIM_STATES = {
  ABIERTO: 'ABIERTO',
  EN_PROCESO: 'EN PROCESO',
  EN_PAUSA: 'EN PAUSA',
  CERRADO: 'CERRADO',
  CANCELADO: 'CANCELADO',
} as const;

export type ClaimState = typeof CLAIM_STATES[keyof typeof CLAIM_STATES];

export const ALL_CLAIM_STATES: ClaimState[] = [
  CLAIM_STATES.ABIERTO,
  CLAIM_STATES.EN_PROCESO,
  CLAIM_STATES.CERRADO,
  CLAIM_STATES.CANCELADO,
  CLAIM_STATES.EN_PAUSA,
];

